spring:
  profiles:
    group:
      "local" : "local, jwt, oauth"
    active : local

---
spring:
  config:
    activate:
      on-profile: "local"

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  server:
    port: 8090

  main:
    allow-circular-references: true

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true

    hibernate:
      ddl-auto: create

  mail:
    host: smtp.naver.com # 이메일 서버 호스트 (Gmail 사용 예)
    port: 587 # SMTP 포트 (Gmail의 경우 465 또는 587)
    username:  # 이메일 계정
    password: # 이메일 계정의 암호 또는 앱 비밀번호 (보안 설정에 따라 다름)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true # TLS를 사용하려면 true, SSL을 사용하려면 false
        debug: true # 디버그 모드 활성화
  logging:
    level:
      root: DEBUG
