spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 729954756779-2usa0d48vh0048r4vmmljtlrlstvcjdh.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email


          naver:
            client-id: jg5_V_oaR2k60xfasDRa
            client-secret: XJ2kRT_oa8
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver


          kakao:
            client-id: bbe971abb2538851ddabe4ef20d76744
            client-secret: oScTITuccuMT1o8C6X4Vv1arBKJkNzSE
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image
            client-name: Kakao


        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id