spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: "local"
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 729954756779-2usa0d48vh0048r4vmmljtlrlstvcjdh.apps.googleusercontent.com
            client-secret: GOCSPX-
            scope: profile, email


          naver:
            client-id: jg5_V_oaR2k60xfasDRa
            client-secret: 
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver


          kakao:
            client-id: bbe971abb2538851ddabe4ef20d76744
            client-secret: 
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image
            client-name: Kakao


        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  main:
    allow-circular-references: true

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        ddl-auto: create

  mail:
    host: smtp.naver.com
    port: 465
    username: dmsthf1225@naver.com
    password: dkffkqb77!!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

jwt:
  secretKey: 'dfadfekndchnsdifqld125654x8sdfnjldsncuelsdfs45x321df'

  access:
    expiration: 360000000 # 1??(60?) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    header: Authorization

  refresh:
    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> ??) * 14(2?))
    header: Authorization-refresh

logging:
  level:
    root: DEBUG

cloud:
  aws:
    credentials:
      accessKey: 
      secretKey: 
    region:
      static: ap-northeast-2
    stack:
      auto: false
  autoconfigure:
    exclude:
      - org.springframework.cloud.aws.autoconfigure.context.ContextInstanceDataAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextCredentialsAutoConfiguration

application:
  bucket:
    name: mos-s3-bucket


